insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Alwyn', 'Elgie', 'aelgie0@sakura.ne.jp', 'Bread', 18, 422003);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Myrtice', 'Kippin', 'mkippin1@slashdot.org', 'Bread', 19, 738053);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Crosby', 'Manuel', 'cmanuel2@google.de', 'Rum', 3, 499530);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Ermentrude', 'Weich', 'eweich3@com.com', 'Oil - Macadamia', 10, 369032);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Meade', 'Vear', 'mvear4@ihg.com', 'Wine - Marlbourough Sauv Blanc', 1, 248846);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Rosco', 'Danielsky', 'rdanielsky5@elegantthemes.com', 'Milk - 2% 250 Ml', 7, 280458);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Lillian', 'Artrick', 'lartrick6@ucla.edu', 'Cheese - Le Cheve Noir', 16, 582764);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Lizabeth', 'McCuish', 'lmccuish7@noaa.gov', 'Sunflower Seed Raw', 2, 339281);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Callida', 'Nossent', 'cnossent8@archive.org', 'Cheese - Comte', 8, 366864);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Osborne', 'Loy', 'oloy9@1688.com', 'Durian Fruit', 3, 595340);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Rodge', 'Ivanovic', 'rivanovica@yelp.com', 'Energy Drink - Franks Original', 4, 471071);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Martin', 'Brigman', 'mbrigmanb@yolasite.com', 'Wine - Malbec Trapiche Reserve', 9, 556951);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Allys', 'Roarty', 'aroartyc@merriam-webster.com', 'Butter - Salted', 8, 814300);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Schuyler', 'Huggin', 'shuggind@wordpress.org', 'Coriander - Ground', 10, 979460);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Noby', 'Hessay', 'nhessaye@nbcnews.com', 'Chicken - Whole', 10, 646647);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Joycelin', 'Kubicka', 'jkubickaf@seattletimes.com', 'Coffee Cup 12oz 5342cd', 14, 615428);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Annadiana', 'Boorer', 'aboorerg@webs.com', 'Butter Ripple - Phillips', 11, 847402);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Katti', 'Oxlee', 'koxleeh@prweb.com', 'Sprouts Dikon', 2, 341492);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Shaine', 'Featherstone', 'sfeatherstonei@archive.org', 'Nut - Hazelnut, Ground, Natural', 3, 585222);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Charlie', 'Franceschino', 'cfranceschinoj@i2i.jp', 'Cheese - Cheddar, Old White', 3, 750995);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Bernita', 'Warr', 'bwarrk@hostgator.com', 'Lighter - Bbq', 8, 737238);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Roman', 'Kohnen', 'rkohnenl@weibo.com', 'Water - Spring Water 500ml', 19, 189378);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Clarissa', 'Phuprate', 'cphupratem@yellowbook.com', 'Island Oasis - Peach Daiquiri', 19, 392037);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Gael', 'Dabinett', 'gdabinettn@dion.ne.jp', 'Sauce - Marinara', 18, 739276);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Dimitry', 'Aspinal', 'daspinalo@disqus.com', 'Bread - Italian Sesame Poly', 16, 61406);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Frederich', 'Rayman', 'fraymanp@issuu.com', 'Carrots - Jumbo', 16, 805035);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Warner', 'D''eath', 'wdeathq@baidu.com', 'Wine - Barossa Valley Estate', 1, 77628);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Pietro', 'Lampbrecht', 'plampbrechtr@ow.ly', 'Soup Campbells Mexicali Tortilla', 14, 782847);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Aridatha', 'Lemerie', 'alemeries@geocities.com', 'Langers - Cranberry Cocktail', 19, 871709);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Hildy', 'Christofol', 'hchristofolt@digg.com', 'Mushroom - Lg - Cello', 19, 20058);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Molly', 'Mattingly', 'mmattinglyu@dot.gov', 'Muffin Chocolate Individual Wrap', 6, 515066);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Peggie', 'Brundrett', 'pbrundrettv@arstechnica.com', 'Pasta - Fettuccine, Egg, Fresh', 2, 526587);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Vladamir', 'Ledes', 'vledesw@tripadvisor.com', 'Pork Ham Prager', 5, 944284);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Cairistiona', 'Locker', 'clockerx@e-recht24.de', 'Asparagus - Frozen', 20, 616356);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Even', 'Passingham', 'epassinghamy@si.edu', 'Maintenance Removal Charge', 4, 19380);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Aurea', 'Erdely', 'aerdelyz@plala.or.jp', 'Muffin - Mix - Bran And Maple 15l', 14, 818578);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Diena', 'Duly', 'dduly10@moonfruit.com', 'Cheese - Mix', 15, 166022);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Barb', 'Scoines', 'bscoines11@stanford.edu', 'Apricots - Dried', 15, 749632);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Maison', 'Moreman', 'mmoreman12@godaddy.com', 'Beef - Flank Steak', 3, 656493);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Andras', 'Stedell', 'astedell13@nasa.gov', 'Burger Veggie', 19, 776188);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Pennie', 'Markos', 'pmarkos14@loc.gov', 'Turkey - Breast, Double', 20, 491891);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Rubia', 'Stork', 'rstork15@ucoz.ru', 'Sugar - Monocystal / Rock', 10, 303023);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Dara', 'Greschke', 'dgreschke16@oakley.com', 'Chicken Giblets', 13, 913912);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Corrine', 'McAless', 'cmcaless17@psu.edu', 'Cut Wakame - Hanawakaba', 15, 270082);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Florentia', 'Pfaff', 'fpfaff18@digg.com', 'Allspice - Jamaican', 5, 481027);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Nancee', 'Swiggs', 'nswiggs19@google.ru', 'Venison - Liver', 13, 53932);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Shena', 'Streight', 'sstreight1a@instagram.com', 'Nut - Hazelnut, Whole', 2, 526372);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Hamlen', 'Molloy', 'hmolloy1b@senate.gov', 'Pastry - Raisin Muffin - Mini', 3, 457602);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Jenine', 'Grassot', 'jgrassot1c@sphinn.com', 'Bagels Poppyseed', 20, 554904);
insert into customer_pivot (firstname, lastname, email, item, quantity, total_price) values ('Ellette', 'Struther', 'estruther1d@goo.gl', 'Watercress', 15, 703926);
